pr:
- main
- release/*

resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-latest
        os: windows
      tsa:
        enabled: false
    stages:
      - stage: Test
        jobs:
        - job: Linux
          pool:
            name: Azure-Pipelines-1ESPT-ExDShared
            image: ubuntu-latest
            os: linux
          steps:
          - template: build/azure-pipelines/linux/build.yml@self

        - job: Windows
          pool:
            name: Azure-Pipelines-1ESPT-ExDShared
            image: windows-latest
            os: windows
          steps:
          - template: build/azure-pipelines/win32/build.yml@self
