trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.18.3'
  displayName: 'Use Node.js 12.18.3'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run lint
    npm run compile
  displayName: 'Compile client'

- script: |
    npm run test
  displayName: 'Run unit tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'util/junit.xml'
    testRunTitle: 'Run unit tests'